global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Nếu alertmanager không deploy, bỏ đi

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app-3n1x.onrender.com']
        labels:
          instance: 'node-app'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://node-app-3n1x.onrender.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-ct2z.onrender.com  # domain public của blackbox exporter
